### ISSUE TITLE
CRUDForm – `formSettings` prop update

### ISSUE THREAD

**Issue by bbtgnn** [dyne/starters#109]
- Rename prop from `formSettings` to `fieldsSettings`
- Add custom labels for fields
- Add custom html attributes for each field
- Rename existing values:
  - fieldsOrder -> order
  - excludedFields -> exclude
  - hiddenFields -> hide
  - ...

**Comment by puria** [comment]
eh... let's do this refactoring as soon as we can... want to implement new webapps, quickly ;p and don't want to refactor again...
