### ISSUE TITLE
feat: RecordsManager `CreateButton` and `EditButton` should have their own `formSettings` prop

### ISSUE THREAD

**Issue by bbtgnn** [dyne/starters#112]
e.g. In `forkbomb/signroom` this allows for multiple `createButton` with different labels and custom attributes (e.g. file field that accepts only pdf, json, etc)

**Comment by puria** [comment]
should be this supersseded by the latest pr?

**Comment by puria** [comment]
Let's rework the issue, by allow not only Create/Edit customization, but also all the modal titles and copywriting of the titles

**Comment by puria** [comment]
Label customization for the fieldmaps
