### ISSUE TITLE
Create migration to change app name in backend

### ISSUE THREAD

**Issue by bbtgnn** [dyne/starters#15]
Custom values should be provided by the user when using cookiecutter.
Things to change:
- App name, Instead of `acme` – http://localhost:8090/_/#/settings
- Email sender name and address – http://localhost:8090/_/#/settings/mail

**Comment by puria** [comment]
https://pocketbase.io/docs/api-settings/

**Comment by bbtgnn** [comment]
Useful reference:

https://pocketbase.io/docs/migrations
https://github.com/pocketbase/pocketbase/discussions/2423
https://github.com/pocketbase/pocketbase/discussions/1191
