### ISSUE TITLE
Refactoring proposal

### ISSUE THREAD

**Issue by bbtgnn** [dyne/starters#174]
This is my proposal for a refactoring. Each point is a folder (module) inside `lib` folder.
They are divided so that in the future each one of them can become a package.

- `pocketbase` – holds `index.ts` (with `pb` and user store) and `types.ts` with all the types
- `pocketbaseToZod` – takes care only of translating the pb schema to zod (I would also move here the script for generating the schema.json)
- `form` – I would like to move this outside of the `components` folder
- `recordForm` (rename of CRUDForm) – takes care of form creation
- `recordsManager` – Mostly what does now, but with reorganized subfolders

`components` and `utils` should become folders where simple stuff is shared across all these modules.
No single files should be left out alone in `lib` folder. Everything should belong to a module

**Comment by puria** [comment]
- collectionTable
- collectionManager
