### ISSUE TITLE
Microservices for DIDroom: initial SWOT analysis 

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/starters#185]
In order to have end-to-end encryption, we need to allow the possibility to offer several microservices in a decentralized fashion. 
This implies that, even if all the initial flows of DIDroom will be executed on the same server, the server domain name (and port) needs to be configured in the backend's .env file, similarly to what we did with Interfacer.  
This a preliminary list of microservices is: 
- External credential issuer(s)  
- Service exposing a list of trusted credential issuers and their DIDs
- List of revoked W3C-VC credentials, the server will return an array of IDs of the revoked credentials  
- Credential serving: when the holder wants to show a W3C-VC, their wallet will query a microservice which will exposes thw W3C-VC credential to an endpoint with a TTL, the TTL (30-60 sec) will be visible on holder's wallet.
- Proxy service, used in various situations (e.g. when the Holder wants to spend a W3C-VC and asks a service to publish it)

Several of this points require further investigation in terms of GUI and deployment, particularly the external credential issuer. This can be further elaborated, possibly while implementing the planned engineerization of the Zenswarm oracles

**Comment by puria** [comment]
The one with a TTL is loosy to me...

**Comment by andrea-dintino** [comment]
> The one with a TTL is loosy to me...

Check the updated version

**Comment by puria** [comment]
Ahaha no it's loosy the idea, to me ;p but as long as we are aware to find another flow...

**Comment by andrea-dintino** [comment]
Moved here:
