### ISSUE TITLE
Add `level` to `OrgAuthorizations` for easier checks (?)

### ISSUE THREAD

**Issue by bbtgnn** [dyne/starters#269]
Instead of doing every time
`auth.name == "admin" || auth.name == "owner"`
we could do
`auth.level <= 1` (owner.level = 0, admin.level = 1)

I think this could be more flexible

**Comment by puria** [comment]
I rememeber we already discussed, this, no? bitwise operator, unix like... to create hierarchy on the roles... get inspired by https://dev.to/jannisdev/build-a-bitwise-permission-system-ocl

**Comment by bbtgnn** [comment]
The thing is, we can’t use bitwise operations in pocketbase api rules

Il giorno sab 28 ott 2023 alle 10:16 Puria Nafisi Azizi <
***@***.***> ha scritto:

**Comment by bbtgnn** [comment]
closed by #322
