### ISSUE TITLE
add inlang

### ISSUE THREAD

**Issue by bbtgnn** [dyne/starters#281]
there is no clear documentation on how to integrate inlang with svelte and typesafe-i18n

**Comment by puria** [comment]
Well I don't want whole inlang, but more precisely the inlnang editor (client side) called fink https://inlang.com/m/tdozzpar/app-inlang-editor#edit-translations-with-version-control-in-a-visual-editor

You can see it in action also in https://inlang.com/editor it just needs the project.inlang.json

**Comment by bbtgnn** [comment]
closed as not relevant
