### ISSUE TITLE
Define location of zenroom contracts

### ISSUE THREAD

**Issue by bbtgnn** [dyne/starters#29]
Is it needed to have zenflows as submodule?
imo, we should have just the contracts we need in the `webapp` subfolder

**Comment by albertolerda** [comment]
Moreover, we (must) have the same submodule in two different places.

**Comment by bbtgnn** [comment]
Git `add submodules` instead of `update` for cookiecutter

**Comment by bbtgnn** [comment]
closed by d687068b5803211891243ab671e21ef84e83d12f
