### ISSUE TITLE
Define keyring save location

### ISSUE THREAD

**Issue by bbtgnn** [dyne/starters#32]
Currently, user `keyring` is saved in localstorage.
Is it okay?

Maybe, saving it in the cookies could be more useful, as they can be used in `.server.ts` pages.
Are there any downsides to this?

**Comment by albertolerda** [comment]
In an e2e crypto environment, the server should not have access to the keyring.

**Comment by puria** [comment]
so localstorage better, that is client only! So we can follow the secure by design principle.
