### ISSUE TITLE
Create a CRUD components

### ISSUE THREAD

**Issue by puria** [dyne/starters#56]
- [x] #57
  The crud table will be in charge to create an automagic view in tabular form with edit/delit button of a pb collection
  It will also have the following props:
  - order_fields
  - hide_fields
  - filter_by
  - css_row
  - css_{fieldname}
  
  with also a slot for adding new fields <slot name="extra_fields">

- [x] #58
  A generated form to edit and create new records in the collection.
  Much a like how [pocketbase/ui](https://github.com/pocketbase/pocketbase/tree/master/ui/src) does.
  Following props needed:
    - order_fields
    - hide_fields
    - filter_by
    - css_form
    - css_{fieldname}

**Comment by bbtgnn** [comment]
closed by #40 #43 #44 #45
